# Google App Engine configuration (alternative to Cloud Run)
runtime: python311
entrypoint: gunicorn --bind :$PORT --workers 4 --timeout 120 run:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  FLASK_ENV: 'production'
  PYTHON_VERSION: '3.11'

handlers:
  - url: /api/.*
    script: auto
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
